### ISSUE TITLE
Một số chỗ chưa được update tiếng việt.

### ISSUE THREAD

**Issue by butinhi** [Belmont-Gabriel/MIUI-12-XML-Vietnamese#11]
1. Thời gian ở stt3
2.  Hiển thị - Lịch trình chế độ tối.
Ảnh dưới
https://ibb.co/M6TFYD8
https://ibb.co/HBbM70r

**Comment by trantuananh1996** [comment]
Đã dịch, update trong bản tới nhé

**Comment by trantuananh1996** [comment]
Commit 0b5eb10585eb79218a01fb2bb7b1d9bd6aac2244
