### ISSUE TITLE
Đặt lịch Chế độ tối chưa dịch hết.

### ISSUE THREAD

**Issue by butinhi** [Belmont-Gabriel/MIUI-12-XML-Vietnamese#12]
Phần cài đặt phía trong : Mặt trời lặn đến mặt trời mọc.
Ảnh dưới.
https://ibb.co/tHTsH3p

**Comment by trantuananh1996** [comment]
#11 nhé

**Comment by trantuananh1996** [comment]
Commit 0b5eb10585eb79218a01fb2bb7b1d9bd6aac2244
