### ISSUE TITLE
Lỗi ứng dụng kép

### ISSUE THREAD

**Issue by maidoanchien** [Belmont-Gabriel/MIUI-12-XML-Vietnamese#2]
Không thể truy cập lưu trữ cho ứng dụng kép.

![Screenshot_2020-06-17-20-02-19-069_com android fileexplorer](https://user-images.githubusercontent.com/67057890/84901291-77a44b80-b0d5-11ea-964f-1fca1d77a91a.jpg)

**Comment by trantuananh1996** [comment]
Lỗi này không phải do gói ngôn ngữ bạn nhé
