### ISSUE TITLE
Displayed issue in recents app screen

### ISSUE THREAD

**Issue by baocaosu** [Belmont-Gabriel/MIUI-12-XML-Vietnamese#3]
Memory status displayed GBB instead of GB
Please fix it. Many thanks
Rom: 12.0.1 stable for Redmi k30 pro

**Comment by baocaosu** [comment]
This issue did not occur if system language had been set to English

**Comment by trantuananh1996** [comment]
Fixed since 20.6.18
Mình đã sửa từ bản 20.6.18 nha

**Comment by trantuananh1996** [comment]
https://github.com/Belmont-Gabriel/MIUI-12-XML-Vietnamese/commit/ce976cc3b66c434c3d5bef74dd78b52d6dcb95e5#diff-19b2b697b430f0d63ed93344451dce0b
