### ISSUE TITLE
Bản dịch MIUI 13

### ISSUE THREAD

**Issue by buiducanh142qn** [Belmont-Gabriel/MIUI-12-XML-Vietnamese#47]
Mình đợi cũng khá là lâu rồi nhưng chưa thấy bản dịch cho MIUI 13. Xài MIUI nửa tiếng Anh nửa tiếng Việt trông hơi khó chịu. Mong bạn mang repo MIUI 13 về sớm cho anh em tham gia dịch

**Comment by buitrungdunghd** [comment]
Mong bạn dịch nốt phần https://github.com/ingbrzy/Xiaomi.eu-MIUIv13-XML-Compare/blob/master/extras/AppVault/strings/strings_en_GB.xml
Nếu có thể cho mình biết cái chỗ này nó nằm ở đâu trong App Vault
Cám ơn bạn

**Comment by butinhi** [comment]
MIUI 13 full TV rồi mà bạn? Bạn dùng rom nào mà nửa TA nửa TV?

**Comment by buiducanh142qn** [comment]
Mình dùng K40S MIUI 13 xiaomi.eu 13.0.10 thấy chưa việt hoá một số chỗ.
1. App vault. Một số Widget hiển thị tiếng Anh, nút thêm Widget (Add to App vault). 
2. Cài đặt. 
- Wi-Fi: Trợ lý Wi-Fi > Thẻ NETWORK ACCELERATION; Cài đặt nâng cao > Wi-Fi region, Wi-Fi trực tiếp (phần mô tả).
- Cài đặt bổ sung > Trợ năng > Nút trợ năng.
- Safety & Emergency.
- Tính năng đặc biệt > Sidebar.
- Tài khoản Mi > Bảo mật tài khoản > Third-party accounts.
3. Mi Smart Hub.
4. Bảo mật > Tăng tốc Trò chơi > Cài đặt > Content recommendations.
5. Quay phim màn hình > Cài đặt > Show button taps.
6. Thư viện > Album > Trong thẻ Sắp xếp ảnh có 2 mục đều là Thùng rác; Nút tìm kiếm > Vị trí tên vẫn hiện tiếng Trung.
7. Tập tin > Cài đặt > Đồng ý chính sách riêng tư (phần mô tả).
8. Máy ảnh > Thêm > Các hiệu ứng: Movie effects, Long exposure; Cài đặt máy ảnh > Tap to take a photo, Preserve settings, Tự khởi chạy (Phần mô tả).
Tạm thời có nhiêu đó, nếu còn nữa thì mình bổ sung.
Mong bạn Việt hoá giúp nhé. Cảm ơn.
