### ISSUE TITLE
Dịch sai 

### ISSUE THREAD

**Issue by maidoanchien** [Belmont-Gabriel/MIUI-12-XML-Vietnamese#5]
Chỗ này phải là dọn dẹp wechat chứ ?
Rom 20.7.30 Mi 9
![IMG_20200802_133850](https://user-images.githubusercontent.com/67057890/89117189-281fb080-d4c6-11ea-8363-56b93c2f1b62.jpg)

**Comment by trantuananh1996** [comment]
Ok để mình xem, có thể nó thay đổi từ lúc nào đấy

**Comment by trantuananh1996** [comment]
Nếu được, bạn đổi sang tiếng Anh và chụp giúp mình một ảnh để dễ tìm nhé

**Comment by maidoanchien** [comment]
Để tiếng Anh thì như thế này
![Screenshot_2020-08-03-12-00-26-697_com miui securitycenter](https://user-images.githubusercontent.com/67057890/89147515-0b947e80-d581-11ea-8324-79542ef3e6eb.jpg)

**Comment by trantuananh1996** [comment]
Thanks bạn, đã fix đẩy vào bản update tới
