### ISSUE TITLE
20.8.13|Mi 9| Cài đặt>Thông báo

### ISSUE THREAD

**Issue by maidoanchien** [Belmont-Gabriel/MIUI-12-XML-Vietnamese#7]
![IMG_20200818_153738](https://user-images.githubusercontent.com/67057890/90490676-19452900-e169-11ea-9502-69bf3b3dc807.jpg)

**Comment by trantuananh1996** [comment]
Ủa sao bạn close rồi, cái này có phải lỗi ko vậy để mình tìm

**Comment by maidoanchien** [comment]
> Ủa sao bạn close rồi, cái này có phải lỗi ko vậy để mình tìm

Qua bản cập nhật mới thì hết r ạ.

**Comment by trantuananh1996** [comment]
Oke bạn nhé
