### ISSUE TITLE
Lỗi hiển thị water mark trên app tin nhắn MIUI - Trên bản MIUI 12 12.0.5.0 dành cho K30 4G (Phoenix)

### ISSUE THREAD

**Issue by nguyentuan125** [Belmont-Gabriel/MIUI-12-XML-Vietnamese#8]
Hi Ad mình gặp lỗi trên app nhắn tin mặc định của MIUI hiện Water Mark "Không có cuộc hội thoại". Ad xem và fix trong bản tiếp theo nhé
![InkedScreenshot_2020-10-28-15-33-26-335_com android mms_LI](https://user-images.githubusercontent.com/73582087/97412331-ffc41880-1933-11eb-8fd3-b2d4db34082e.jpg)

**Comment by trantuananh1996** [comment]
Cái này mình nghĩ ko phải lỗi của gói ngôn ngữ
