### ISSUE TITLE
Dịch sai, app mi mover, mi 9 rom 20.11.05

### ISSUE THREAD

**Issue by maidoanchien** [Belmont-Gabriel/MIUI-12-XML-Vietnamese#9]
Phải dịch là cũ với mới chứ ạ.
![Screenshot_2020-11-06-17-15-58-878_com miui huanji](https://user-images.githubusercontent.com/67057890/98355134-53311780-2054-11eb-9fff-4cc81921ad2c.jpg)

**Comment by trantuananh1996** [comment]
Cảm ơn bạn để mình check nhé

**Comment by trantuananh1996** [comment]
Đã thấy, sẽ sửa trong bản update tuần tới bạn nhé
